file from homework_4
eugene-okulik/Yuryi pull request #3
Opened 2024-12-24 16:58 UTC by yurilopa

Country, city and transport for homework_4

2024-12-25 10:02 UTC, eugene-okulik requested changes

2024-12-25 10:02 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_4/basics_2.py
> +my_inside_dict['i_am_a_tuple'] = 'add_new_tuple'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i_am_a_tuple'`

2024-12-25 10:02 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_4/basics_2.py
> +my_inside_dict = {'RU': 'Msk', 'KZ': 'Atyrau', 'KZ2': 'Almaty', 'TH': 'Sammui', 'for_delite': 'this_is_for_delite'}
Идея в том, что my_dict будет хранить всё это, а не только строки с названиями.  
То есть было бы так:
```python
my_dict = {
    'tuple': ('RU', 'KZ', 'UZ', 'TH', 'last_element'),
    'list': [1, '2_for_delite_element', 3, 4, 5],
    'dict': {'RU': 'Msk', 'KZ': 'Atyrau', 'KZ2': 'Almaty', 'TH': 'Sammui', 'for_delite': 'this_is_for_delite'},
    'set': {'taxi', 'air', 'boat', 'motobike', 'bikecircle'}
}
```
Тогда, выполнение, например, первого задания выглядело бы так
```python
my_dict['list'].append('new_item')
```

2024-12-25 17:58 UTC, yurilopa commented
Переделал дз

2024-12-26 06:12 UTC, yurilopa commented
еще раз переделал)

2024-12-26 07:02 UTC, eugene-okulik requested changes

2024-12-26 07:02 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_4/basic_2_renew.py
> +my_dict['dict']['new_key'] = ('i am a tuple',)
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты добавил элемент с ключом 'new_key' и значением ('i am a tuple',)  
То, что сейчас у тебя в значении, должно быть ключом. А значение - вообще не важно какое будет.

2024-12-27 05:02 UTC, yurilopa commented
Добавил проверки, сейчас вроде все правильно сделал.

2024-12-27 07:04 UTC, eugene-okulik requested changes

2024-12-27 07:04 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_4/basic_2_renew.py
> +my_dict['dict']['i am a tuple'] = 'New values'
А сейчас у тебя ключ - строка `'i am a tuple'`, а должен быть кортеж `('i am a tuple',)`

2024-12-27 12:26 UTC, yurilopa commented
Еще раз переделал, меня смутило что при выводе (my_dict['dict']) написание tuple отличается от всех других пар ключ-значение. Но видимо так и должно было быть.

2024-12-28 09:19 UTC, eugene-okulik approved these changes
На этом задании многие застревают. Я его сделал специально, чтобы закрепилось две вещи:
1. tuple (кортеж) может быть ключом словаря
2. tuple (кортеж) с одним значением выглядит так

2024-12-28 09:19 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_4/basic_2_renew.py
> +print(('i am a tuple',) in my_dict['dict'].values())
Это какие-то эксперименты, да?

2024-12-28 09:19 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_4/basic_2_renew.py
> +my_dict = \
Этот обратный слеш лишний. PEP-8 не рекомендует им пользоваться. Правильнее всего вот так:
```python
my_dict = {
    'tuple': ('RU', 'KZ', 'UZ', 'TH', 'last_element'),
    'list': [1, '2_for_delite_element', 3, 4, 5],
    'dict': {'RU': 'Msk', 'KZ': 'Atyrau', 'KZ2': 'Almaty', 'TH': 'Sammui', 'for_delite': 'this_is_for_delite'},
    'set': {'taxi', 'air', 'boat', 'motobike', 'bikecircle'}
}
```

2024-12-28 09:19 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_4/basic_2_renew.py
> +my_dict['dict']['i am a tuple',] = 'New values'
Отлично!

2024-12-28 09:19 UTC, merged

2024-12-28 09:44 UTC, yurilopa commented on homework/yuryi_lopatin/homework_4/basic_2_renew.py
> +print(('i am a tuple',) in my_dict['dict'].values())
Я тут решил проверить что ('i am a tuple',) действительно ключ перед тем как отправлять.