homework_5
eugene-okulik/Yuryi pull request #4
Opened 2024-12-31 05:33 UTC by yurilopa

homework

2024-12-31 07:20 UTC, eugene-okulik requested changes

2024-12-31 07:20 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +country = person[4]
Обращаться к элементам списка - последнее дело. В этой ситуации, когда мы четко знаем сколько элементов в списке и что находится на каждой позиции, лучше всего воспользоваться распаковкой, о которой я рассказывал на занятии.

2024-12-31 07:20 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +print(result[0] + 10, result[1] + 10, result[2] + 10)
Идея в том, чтобы написать программу, которая сама найдет в данной строке число и сделает с этим числом то, что нужно. Схематично, это будет выглядеть так:
```python
str1 = 'результат операции: 42'
str2 = 'результат операции: 514'
str3 = 'результат работы программы: 9'

num1 = как-то получаем число из str1
num2 = копируем код из num1 и получаем число из str2
num3 = копируем код из num1 и получаем число из str3

print(str1 + 10)
print(str2 + 10)
print(str3 + 10)


```

2024-12-31 07:20 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +subjects = ', '.join(subjects)
:+1:

2025-01-03 07:43 UTC, eugene-okulik requested changes

2025-01-03 07:43 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +a, b, c, d, e = person
Отлично, только нужно привыкать давать говорящие имена переменным, чтобы было понятно, что под ними хранится:
```python
name, last_name, city, phone, country = person
```

2025-01-03 07:43 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +num3 = str3.split(':')[1]
Это самое оптимальное решение этого задания. Если бы в задании не было указано с помощью чего нужно его решить, то этот вариант был бы самым лучшим. Но нужно решить с использованием index и срезов.

2025-01-04 06:40 UTC, yurilopa commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +a, b, c, d, e = person
исправил

2025-01-04 06:41 UTC, yurilopa commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +num3 = str3.split(':')[1]
А я еще голову ломал, почему в третьей строчки текст отличается)

2025-01-04 09:16 UTC, eugene-okulik requested changes

2025-01-04 09:16 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +print(int(num3) + 10)
`num1 = (str1.index('42'))`  вычисляет индекс позиции числа 42 в этой строке, а потом ты к этому индексу плючуешь 10 вот здесь `print(int(num1) + 10)`  
Но нужно 10 прибавить не к индексу позиции числа. С помощью индекса нужно поулчить само число и к нему прибавить 10.  
В том виде, как сделано у тебя, это было бы так
```python
index1 = (str1.index('42'))
num1 = str[index1:]  # Это срез, с помощью которого мы берем из этой строки всё с того места, где начинается число и до конца
print(int(num1) + 10)
```
Но такое решение я тоже не приму, так как если мы и так, еще при написании кода, знаем, что в строке число 42, то зачем нам его оттуда получать. Задумка в том, что число может быть любое: вместо 42 может оказаться число 3456543, а вместо 514 число 3. Поэтому нужно найти в этих строках что-то одинаковое и, опираясь на это получать из строк числа. Одинаковое ты уже нашел в прошлом выполнении - это двоеточия. Число всегда идет после него. То есть мы сможем получить число если возьмем всё содержимое строки от двоеточия и до конца (только нужно будет избавиться от двоеточия в полученном результате)

2025-01-05 09:40 UTC, eugene-okulik requested changes

2025-01-05 09:40 UTC, eugene-okulik commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +num3 = (str3[28::])
Индекс, с которого нужно вычитывать хранится у тебя в переменных index1, index2, index3, если строка 1 будет содержать текст 'результат работы программы: 9', то код отработает неправильно. А вот если вместо того, чтобы написать `num1 = (str1[20::])`, сделать `num1 = (str1[index1::])`, то будет абсолютно неважно какой из вариантов строки окажется в переменной str1.

2025-01-07 13:06 UTC, eugene-okulik approved these changes
Круто. Теперь всё правильно. Ну что, как ощущения? Как тебе дается программирование?  
Напиши мне в телеграм - обсудим.

2025-01-07 13:06 UTC, merged

2025-01-08 07:45 UTC, yurilopa commented on homework/yuryi_lopatin/homework_5/basic_3.py
> +num3 = (str3[28::])
Дописал переменную index[1, 2, 3] вместо str1[20::]